[package]
name = "zerolog"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
chrono = "0.4"

[[bin]]
name = "main"
path = "src/main.rs"
